### ISSUE TITLE
Problem running ansible xroad-ca in a clean machine

### ISSUE THREAD

**Issue by nanndoj** [nordic-institute/X-Road#186]
### Issue

I am facing an error when trying to install the role `xroad-ca` in a clean machine from GCP. This is because the fresh machine GCP comes with outdated repositories. 

### How to reproduce
Try to run the ansible script on any fresh machine from GCP

### Expected Result
The script should run without problems

### Actual Result
```
failed: [ca.xvia.com.br] (item=nginx-light) => {"ansible_loop_var": "item", "changed": false, "item": "nginx-light", "msg": "No package matching 'nginx-light' is available"}
```

### Possible solution
Force apt to update the packages before trying to install the new packages.

```yaml
- name: Update all packages to the latest version
  apt:
    update_cache: yes
```
