### ISSUE TITLE
Asking help about the IP in Security Server and Central server?

### ISSUE THREAD

**Issue by Faqihyugos** [nordic-institute/X-Road#2157]
# Help me

hello iam faqih newbie xroad implement on my office.

why can't upload anchor on security server. this error : Configuration source cannot be reached, check source URL in uploaded anchor file.
enviroment on  docker compose local and ip private.

<img width="1680" alt="Screenshot 2024-05-13 at 10 55 05" src="https://github.com/nordic-institute/X-Road/assets/32142762/b81f13aa-0630-4ccc-9769-d1005fed0a97">

setting cs and ss guide link : https://nordic-institute.atlassian.net/wiki/spaces/XRDKB/pages/215875585/How+to+Configure+Central+Server+version+7.3.0

## this docker compose 

```yml

version: '3.8'
services:
  cs:
    image: niis/xroad-central-server:jammy-7.4.2
    ports:
      - "80:80"
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "8888:8888"
      - "8899:8899"
    container_name: cs
  ss:
    image: niis/xroad-security-server:jammy-7.4.0
    ports:
      - "8080:8080"
      - "8443:8443"
      - "4003:4000"
      - "5500:5500"
      - "5577:5577"
    container_name: ss

```
